### PR TITLE
fix(next): one line voting display

### LINKED ISSUE #670: Optimize the voting results display
Make sure voting options and votes are displayed on one line, and the overflow text is replaced with an ellipsis. Display the full voting options in tooltip。

[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=3658%3A22330)

Preview
[Source](https://voting.opensquare.io/space/rmrk-curation/proposal/QmSy1fKtMoutrDv3cwhCG44Q2bzgiLUpKen5hvfbyJXupL)
image
image

### PR DESCRIPTION
**Pull request by 2nthony**
close #670

### CODE REVIEW

**Comment by 2nthony** [comment]
image

File: packages/next/components/postDetail/biasedVotingItem.js [hunk 1]
```diff
@@ -22,13 +22,22 @@ const LabelWrapper = styled.div`
   }
 `;
 
-function BiasedVotingItem({ label, value, space }) {
+function BiasedVotingItem({ label = "", value, space }) {
+  const Label = <div className="label">{label}</div>;
```
Comment (YoshiyukiSakura) [inline packages/next/components/postDetail/biasedVotingItem.js:26]: we don't capitalize  regular variables ,  only contants & tags shall be capitalized.
in this case, `Label` is a element rather than a tag name

maybe name it `displayLabel` ?

Comment (2nthony) [reply packages/next/components/postDetail/biasedVotingItem.js:26]: in a minute

File: packages/next/components/postDetail/biasedVotingItem.js [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+function BiasedVotingItem({ label = "", value, space }) {
+  const displayLabel = <div className="label">{label}</div>;
+
+  return (
+    <Wrapper>
+      <LabelWrapper>
+        {/*
+          TODO: Should refactor, this is not a smart way to show the tooltip or not
+        */}
+        {label.length > 10 ? (
```
Comment (2nthony) [inline packages/next/components/postDetail/biasedVotingItem.js:34]: @YoshiyukiSakura is this necessary? if yes, how many characters should show the tooltip?

File: packages/next/components/postDetail/biasedVotingItem.js [hunk 3]
```diff
@@ -0,0 +1,48 @@
+import styled from "styled-components";
+import Tooltip from "../tooltip";
+import ValueDisplay from "../valueDisplay";
+
+const Wrapper = styled.div`
+  position: relative;
+  display: flex;
+  justify-content: space-between;
+  align-item: center;
```
Comment (YoshiyukiSakura) [inline packages/next/components/postDetail/biasedVotingItem.js:9]: typo

File: packages/next/components/postDetail/biasedVotingItem.js (hunk 2 above)
Comment (YoshiyukiSakura) [reply packages/next/components/postDetail/biasedVotingItem.js:34]: its not a good approach, since `ABCDE` is much wider than `iiiii` yet they both count as `5`

File: packages/next/components/postDetail/biasedVotingItem.js [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+  position: relative;
+  display: flex;
+  width: 60%;
+
+  // for tooltip with size=fit
+  > *:first-child {
+    max-width: 100%;
+  }
+
+  .label {
```
Comment (YoshiyukiSakura) [inline packages/next/components/postDetail/biasedVotingItem.js:23]: class defination here isn't combined with any other styled-component, may just difine a `const Label = style.div` and apply these css within it
